- name: Create certificate for a client
  shell: easyrsa build-client-full {{ hostvars[item]['ansible_default_ipv4']['address'] }} nopass
  run_once: yes
  args:
    chdir: /root
    creates: "{{ PKI_DIR }}/issued/{{ hostvars[item]['ansible_default_ipv4']['address'] }}.crt"
  environment:
    PATH: "{{ EASY_RSA_BIN }}/{{ EASY_RSA_ARCH_DIR }}:{{ ansible_env.PATH }}"
  with_items: "{{ groups['client'] }}"
  delegate_to: "{{ easy_rsa_host }}"

- name: Grab client cert locally
  fetch:
    src: "{{PKI_DIR}}/issued/{{ ansible_host }}.crt"
    dest: "{{ local_repo }}/clients/issued/"
    flat: yes
  delegate_to: "{{ easy_rsa_host }}"

- name: Grab keys locally
  fetch:
    src: "{{PKI_DIR}}/private/{{ ansible_host }}.key"
    dest: "{{ local_repo }}/clients/private/"
    flat: yes
  delegate_to: "{{ easy_rsa_host }}"
