---
# tasks file for openvpn-easyrsa


- name: Create easyrsa dir if it deosnt exists
  file:
    path: "{{ EASY_RSA_BIN }}"
    state: directory
    mode: '0770'

- name: Install easy rsa
  get_url:
    url: "https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.6/{{ EASY_RSA_VERSION }}.tgz"
    dest: "{{ EASY_RSA_BIN }}"

- name: Extract easyrsa
  unarchive:
    src: "{{ EASY_RSA_BIN }}/{{ EASY_RSA_VERSION }}.tgz"
    dest: "{{ EASY_RSA_BIN }}/"
    remote_src: yes
    creates: "{{ EASY_RSA_BIN }}/{{ EASY_RSA_ARCH_DIR }}"

- name: Init PKI
  shell: echo 'yes' | easyrsa init-pki
  args:
    chdir: /root
    creates: "{{ PKI_DIR }}"
  environment:
    PATH: "{{ EASY_RSA_BIN }}/{{ EASY_RSA_ARCH_DIR }}:{{ ansible_env.PATH }}"

- name: Build CA
  expect:
    command: easyrsa build-ca nopass
    chdir: /root
    creates: "{{ PKI_DIR }}/ca.crt"
    responses:
      'Common Name \(eg: your user, host, or server name\) \[Easy-RSA CA\]:$': "ca"
  environment:
    PATH: "{{ EASY_RSA_BIN }}/{{ EASY_RSA_ARCH_DIR }}:{{ ansible_env.PATH }}"

- name: Generate secret
  command: openvpn --genkey --secret {{ PKI_DIR }}/ta.key
  args:
    creates: "{{ PKI_DIR }}/ta.key"

- name: Grab CA locally
  fetch:
    src: "{{ PKI_DIR }}/ca.crt"
    dest: "{{ LOCAL_REPO }}/"
    flat: yes

- name: Grab ta locally
  fetch:
    src: "{{PKI_DIR}}/ta.key"
    dest: "{{ LOCAL_REPO }}/"
    flat: yes



