---
# tasks file for openvpn-easyrsa
- name: Install easy rsa
  apt:
    name: easy-rsa=2.2.2-2

- name: Check repo prepared
  stat:
    path: "{{ PKI_DIR }}"
  register: pki_repo_exists

- name: Prepare pki repo
  shell: cp -r "{{ EASY_RSA_BIN }}" "{{ PKI_DIR }}"
  when: pki_repo_exists.stat.exists == False

- name: Configure PKI
  template:
    src: templates/vars
    dest: "{{ PKI_DIR }}/vars"
    mode: '0760'

- name: Build CA
  shell: ln -s openssl-1.0.0.cnf openssl.cnf ; source ./vars ; ./clean-all ; ./build-ca --batch
  args:
    chdir: "{{ PKI_DIR }}"
    creates: keys
  environment:
    PATH: "{{ EASY_RSA_BIN }}:{{ ansible_env.PATH }}"
