---
# tasks file for openvpn-easyrsa

- name: Install dependencies
  import_tasks: deps.yml
  when: >
    inventory_hostname == easy_rsa_host
    and ansible_distribution == 'Debian'

- name: Use debian related tasks if appropriete
  import_tasks: debian.yml
  when: >
    inventory_hostname == easy_rsa_host
    and ansible_distribution == 'Debian'

- name: Client utility tasks
  import_tasks: clientUtils.yml
  when: >
    inventory_hostname == easy_rsa_host
    and ansible_distribution == 'Debian'
    and client_type is defined

- name: server utility tasks
  import_tasks: serverUtils.yml
  when: >
    inventory_hostname == easy_rsa_host
    and ansible_distribution == 'Debian'