---
# tasks file for openvpn-easyrsa

- name: Use debian 10 related tasks if appropriete
  import_tasks: debian10.yml
  when: >
    inventory_hostname == easy_rsa_host
    and ansible_distribution == 'Debian'
    and ansible_distribution_release == 'buster'

- name: Use debian 9 related tasks if appropriete
  import_tasks: debian9.yml
  when: >
    inventory_hostname == easy_rsa_host
    and ansible_distribution == 'Debian'
    and ansible_distribution_release == 'stretch'