- name: Generate diffie helman for a server
  command: openssl dhparam -out {{ PKI_DIR }}/dh_{{ server_host }}.pem {{ DH_LEN }}
  args:
    creates: "{{ PKI_DIR }}/dh_{{ server_host }}.pem"

- name: Create certificates for a server
  command: easyrsa --subject-alt-name="{{ id_type }}:{{ server_host }}" build-server-full {{ server_host }} nopass
  args:
    chdir: /root
    creates: "{{ PKI_DIR }}/issued/{{ server_host }}.crt"
  environment:
    PATH: "{{ EASY_RSA_BIN }}/{{ EASY_RSA_ARCH_DIR }}:{{ ansible_env.PATH }}"

- name: Create server personalized template directory
  file:
    path: "{{ SERVER_CFG_DIR }}"
    state: directory
    mode: '0770'

- name: Template servers
  template:
    src: templates/server.conf
    dest: "{{ SERVER_CFG_DIR }}/{{ server_host }}.conf"
    mode: '0660'
    force : false

- name: Grab server certs locally
  fetch:
    src: "{{PKI_DIR}}/issued/{{ server_host }}.crt"
    dest: "{{ LOCAL_REPO }}/servers/issued/"
    flat: yes

- name: Grab server keys locally
  fetch:
    src: "{{PKI_DIR}}/private/{{ server_host }}.key"
    dest: "{{ LOCAL_REPO }}/servers/private/"
    flat: yes

- name: Grab dh locally
  fetch:
    src: "{{PKI_DIR}}/dh_{{ server_host }}.pem"
    dest: "{{ LOCAL_REPO }}/servers/"
    flat: yes

- name: Grab server config locally
  fetch:
    src: "{{ SERVER_CFG_DIR }}/{{ server_host }}.conf"
    dest: "{{ LOCAL_REPO }}/servers/"
    flat: yes