- name: Create certificates for a server
  command: easyrsa --subject-alt-name="{{ id_type }}:{{ ansible_host }}" build-server-full {{ ansible_host }} nopass
  args:
    chdir: /root
    creates: "{{ PKI_DIR }}/issued/{{ ansible_host }}.crt"
  environment:
    PATH: "{{ EASY_RSA_BIN }}/{{ EASY_RSA_ARCH_DIR }}:{{ ansible_env.PATH }}"
  delegate_to: "{{ easy_rsa_host }}"

- name: Grab server certs locally
  fetch:
    src: "{{PKI_DIR}}/issued/{{ ansible_host }}.crt"
    dest: "{{ LOCAL_REPO }}/servers/issued/"
    flat: yes
  delegate_to: "{{ easy_rsa_host }}"

- name: Grab server keys locally
  fetch:
    src: "{{PKI_DIR}}/private/{{ ansible_host }}.key"
    dest: "{{ LOCAL_REPO }}/servers/private/"
    flat: yes
  delegate_to: "{{ easy_rsa_host }}"
